### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by lutzer** [DigitalArsenal/node-red-contrib-static#1]
Hey,

i would love to use your node, but it gives me the following error: `[error] [static:bb412dfb.2edcd] TypeError: Cannot read property '0' of null`

Im trying this very basic example flow:

`[{"id":"7730d6a6.4b11e8","type":"static","z":"c2f9198a.b74648","name":"","folder":"/Users/lutz/Projects/drl-tools/modules/tablet-frontend/dist/","x":530,"y":300,"wires":[["c856a66e.20c0d8"]]},{"id":"89928479.2c90c8","type":"http in","z":"c2f9198a.b74648","name":"","url":"test/:path","method":"get","upload":false,"swaggerDoc":"","x":340,"y":300,"wires":[["7730d6a6.4b11e8"]]},{"id":"c856a66e.20c0d8","type":"http response","z":"c2f9198a.b74648","name":"","statusCode":"","headers":{},"x":750,"y":300,"wires":[]}]`

Am i doing something wrong? I looked at your code and I read through the serve-static docs but i dont really understand which property of the request object is used to construct the local fiepath. i think the problem should be in line 21 of static.js

**Comment by TJKoury** [comment]
Thanks for the pull, this issue should be resolved.
